export const ADD_TO_DRAWER = "ADD_TO_DRAWER"
export const DECREMENT_FROM_DRAWER = "DECREMENT_FROM_DRAWER"
export const ACTIVE_BUTTON = "ACTIVE_BUTTON"
export const ITEM_LENGTH = "ITEM_LENGTH"
export const CROSS_ICON = "CROSS_ICON"
export const MODEL_ITEM = "MODEL_ITEM"
///////////////AdminPanel////////
export const PRODUCT_CREATED_BY_ADMIN = "PRODUCT_CREATED_BY_ADMIN"
export const FETCH_DATA_LOADING = "FETCH_DATA_LOADING"




